
peso = float
altura = float
imc = float
peso = float(input("Qual o seu peso? :"))
altura= float(input("Qual é a sua altura? :"))

imc = ( peso/(altura*altura))
x = round(imc,2)
print("Seu IMC é: ",x)

if x < 16 :
    print("Magreza Grave")
elif imc < 17 :
    print("Magreza Moderada")
elif imc < 18.5:
    print("Magreza Leve")
elif imc < 25 :
    print("Saudável")
elif imc < 30:
    print("Sobrepeso")
elif imc < 35 :
    print("Obesidade Grau I")
elif imc < 40:
    print("Obesidade Grau II")
else:
    print("Obesidade Grau III")


# Nome : Felipe Francisco de Oliveira Costa     
#RA : 2217114084
